%% A matlab script for vizualizing delay times(between transaction and storing)

%% Script for importing data from the following text file:
%
%    filename: C:\Users\Christos\chris\auth\Embeded and real time systems\LWSproject\storing_times.txt
%
% Auto-generated by MATLAB on 08-Oct-2022 12:46:49

% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "storing_times";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("C:\Users\Christos\chris\auth\Embeded and real time systems\LWSproject\storing_times.txt", opts);

% Convert to output type
storing_times = tbl.storing_times;

% Clear temporary variables
clear opts tbl





%% Script for importing data from the following text file:
%
%    filename: C:\Users\Christos\chris\auth\Embeded and real time systems\LWSproject\lws_times.txt
%
% Auto-generated by MATLAB on 08-Oct-2022 12:51:02

% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("C:\Users\Christos\chris\auth\Embeded and real time systems\LWSproject\lws_times.txt", opts);

% Convert to output type
lws_times = tbl.VarName1;

% Clear temporary variables
clear opts tbl



%% Processing
% the delays are in milliseconds
delays = storing_times - lws_times;


%% Vizualizing
n = size(lws_times); % the number of the samples
X = 1:n; % x-axis
plot(X, delays,"-.r"); % plot the delays
set(gca, 'Color', 'k'); % plot's background color to black
m_val = mean(delays);
var_val = var(delays);
string = ["Mean value is: ", m_val, "and the variance is: ", var_val];
disp(string);